### ISSUE TITLE
Visualize an item's float in a float-bar

### ISSUE THREAD

**Issue by GODrums** [csfloat/extension#272]
## Description
The item float is an important concept to understand when classifying an item. Usually the float is a floating-point number between 0 and 1, although this can vary on a skin-to-skin basis.
Within this issue, the following should be addressed:
- visualizing floats similar to CSFloat's float bar design:
  ![Image](https://github.com/user-attachments/assets/3df0e0cf-0e09-49a9-a945-d7f1a49801b1)
- explicitly limit the bar at the skins's unique float caps
- support Steam market pages as well as the Steam inventory page

## Tasks

- [ ] Design a Float bar independent of a fixed width parent container
- [ ] Get access to the min/max float caps of skins
- [ ] Adjust Steam Market pages
  - [ ] Access min/max float caps
  - [ ] Add float bar to each market listing
- [ ] Adjust Steam Inventory page
  - [ ] Access min/max float caps
  - [ ] Add float bar to the focused item section
